---
Name: search
---
SilverStripe\Control\Controller:
  extensions:
    - Jaedb\Search\SearchControllerExtension
Jaedb\Search\SearchPageController:
  types:
    pages:
      Label: 'Pages'
      ClassName: 'Page'
      Table: 'Page_Live'
      Filters: 
        SiteTree_Live.ShowInSearch: '1'
      JoinTables: ['SiteTree_Live']
      Columns: ['SiteTree_Live.Title','SiteTree_Live.MetaDescription','SiteTree_Live.MenuTitle','SiteTree_Live.Content']